"""Static metadata for V0.3.0 framework error codes."""

from __future__ import annotations

from typing import NamedTuple


class ErrorCodeMetadata(NamedTuple):
    code: str
    level: str
    stage: tuple[str, ...]
    doc_link: str


ERROR_REGISTRY: dict[str, ErrorCodeMetadata] = {
    '[F-v3-graph-schema-unknown-field]': ErrorCodeMetadata('[F-v3-graph-schema-unknown-field]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-name-invalid]': ErrorCodeMetadata('[F-v3-graph-name-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-schema-version-mismatch]': ErrorCodeMetadata('[F-v3-graph-schema-version-mismatch]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-llm-role-unknown]': ErrorCodeMetadata('[F-v3-graph-llm-role-unknown]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-root-missing]': ErrorCodeMetadata('[F-v3-graph-root-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/01-physical-layout/mvp1-alignment.md#21-skill-源码树'),
    '[F-v3-graph-phases-dir-missing]': ErrorCodeMetadata('[F-v3-graph-phases-dir-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/01-physical-layout/mvp1-alignment.md#21-skill-源码树'),
    '[F-v3-graph-phases-missing]': ErrorCodeMetadata('[F-v3-graph-phases-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-phase-id-invalid]': ErrorCodeMetadata('[F-v3-graph-phase-id-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-phase-name-mismatch]': ErrorCodeMetadata('[F-v3-graph-phase-name-mismatch]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-phase-id-duplicate]': ErrorCodeMetadata('[F-v3-graph-phase-id-duplicate]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-depends-unknown]': ErrorCodeMetadata('[F-v3-graph-depends-unknown]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-output-phase-invalid]': ErrorCodeMetadata('[F-v3-graph-output-phase-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-phase-cycle]': ErrorCodeMetadata('[F-v3-graph-phase-cycle]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-phase-island]': ErrorCodeMetadata('[F-v3-graph-phase-island]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-phase-dir-missing]': ErrorCodeMetadata('[F-v3-graph-phase-dir-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/01-physical-layout/mvp1-alignment.md#21-skill-源码树'),
    '[F-v3-graph-phase-mode-ambiguous]': ErrorCodeMetadata('[F-v3-graph-phase-mode-ambiguous]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/01-physical-layout/mvp1-alignment.md#21-skill-源码树'),
    '[F-v3-graph-phase-node-missing]': ErrorCodeMetadata('[F-v3-graph-phase-node-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/01-physical-layout/mvp1-alignment.md#21-skill-源码树'),
    '[F-v3-graph-io-not-object]': ErrorCodeMetadata('[F-v3-graph-io-not-object]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-io-schema-invalid]': ErrorCodeMetadata('[F-v3-graph-io-schema-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-graph-io-physical-file-deprecated]': ErrorCodeMetadata('[F-v3-graph-io-physical-file-deprecated]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/01-physical-layout/mvp1-alignment.md#21-skill-源码树'),
    '[F-v3-graph-dataflow-source-missing]': ErrorCodeMetadata('[F-v3-graph-dataflow-source-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-compile-recursion-cycle]': ErrorCodeMetadata('[F-v3-compile-recursion-cycle]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/03-compile-rules/mvp1-alignment.md#compile-domain'),
    '[F-v3-compile-depth-exceeded]': ErrorCodeMetadata('[F-v3-compile-depth-exceeded]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/03-compile-rules/mvp1-alignment.md#compile-domain'),
    '[F-v3-logic-schema-unknown-field]': ErrorCodeMetadata('[F-v3-logic-schema-unknown-field]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-name-invalid]': ErrorCodeMetadata('[F-v3-logic-name-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-io-schema-invalid]': ErrorCodeMetadata('[F-v3-logic-io-schema-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-actions-empty]': ErrorCodeMetadata('[F-v3-logic-actions-empty]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-action-name-invalid]': ErrorCodeMetadata('[F-v3-logic-action-name-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-action-dir-missing]': ErrorCodeMetadata('[F-v3-logic-action-dir-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-action-not-found]': ErrorCodeMetadata('[F-v3-logic-action-not-found]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-action-entrypoint-missing]': ErrorCodeMetadata('[F-v3-logic-action-entrypoint-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-action-purity-violation]': ErrorCodeMetadata('[F-v3-logic-action-purity-violation]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-action-return-invalid]': ErrorCodeMetadata('[F-v3-logic-action-return-invalid]', 'FATAL', ('运行期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-output-field-undeclared]': ErrorCodeMetadata('[F-v3-logic-output-field-undeclared]', 'FATAL', ('运行期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-validator-type-invalid]': ErrorCodeMetadata('[F-v3-logic-validator-type-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-validator-missing]': ErrorCodeMetadata('[F-v3-logic-validator-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-validator-entrypoint-missing]': ErrorCodeMetadata('[F-v3-logic-validator-entrypoint-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-logic-validator-failed]': ErrorCodeMetadata('[F-v3-logic-validator-failed]', 'FATAL', ('运行期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-validator-failed]': ErrorCodeMetadata('[F-v3-agent-validator-failed]', 'FATAL', ('运行期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-subgraph-validator-failed]': ErrorCodeMetadata('[F-v3-subgraph-validator-failed]', 'FATAL', ('运行期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-subgraph-schema-unknown-field]': ErrorCodeMetadata('[F-v3-subgraph-schema-unknown-field]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-subgraph-name-invalid]': ErrorCodeMetadata('[F-v3-subgraph-name-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-subgraph-target-skill-invalid]': ErrorCodeMetadata('[F-v3-subgraph-target-skill-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#21-子图-path-引用契约mvp1-权威'),
    '[F-v3-subgraph-io-schema-invalid]': ErrorCodeMetadata('[F-v3-subgraph-io-schema-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#21-子图-path-引用契约mvp1-权威'),
    '[F-v3-subgraph-io-mismatch]': ErrorCodeMetadata('[F-v3-subgraph-io-mismatch]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#21-子图-path-引用契约mvp1-权威'),
    '[F-v3-subgraph-io-schema-incompatible]': ErrorCodeMetadata('[F-v3-subgraph-io-schema-incompatible]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#21-子图-path-引用契约mvp1-权威'),
    '[F-v3-agent-schema-unknown-field]': ErrorCodeMetadata('[F-v3-agent-schema-unknown-field]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-name-invalid]': ErrorCodeMetadata('[F-v3-agent-name-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-llm-role-unknown]': ErrorCodeMetadata('[F-v3-agent-llm-role-unknown]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-io-schema-invalid]': ErrorCodeMetadata('[F-v3-agent-io-schema-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-output-schema-invalid]': ErrorCodeMetadata('[F-v3-agent-output-schema-invalid]', 'FATAL', ('运行期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-output-schema-missing]': ErrorCodeMetadata('[F-v3-agent-output-schema-missing]', 'FATAL', ('运行期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-tool-unknown]': ErrorCodeMetadata('[F-v3-agent-tool-unknown]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-subagent-invalid]': ErrorCodeMetadata('[F-v3-agent-subagent-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-subgraph-invalid]': ErrorCodeMetadata('[F-v3-agent-subgraph-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-max-iterations-invalid]': ErrorCodeMetadata('[F-v3-agent-max-iterations-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-body-tag-unknown]': ErrorCodeMetadata('[F-v3-agent-body-tag-unknown]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-role-missing]': ErrorCodeMetadata('[F-v3-agent-role-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-goal-missing]': ErrorCodeMetadata('[F-v3-agent-goal-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-step-invalid]': ErrorCodeMetadata('[F-v3-agent-step-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-protocol-invalid]': ErrorCodeMetadata('[F-v3-agent-protocol-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-agent-example-invalid]': ErrorCodeMetadata('[F-v3-agent-example-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-mention-type-unknown]': ErrorCodeMetadata('[F-v3-mention-type-unknown]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-mention-syntax-invalid]': ErrorCodeMetadata('[F-v3-mention-syntax-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-mention-target-not-found]': ErrorCodeMetadata('[F-v3-mention-target-not-found]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-mention-unused-registry-entry]': ErrorCodeMetadata('[F-v3-mention-unused-registry-entry]', 'WARN', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-resource-reference-invalid]': ErrorCodeMetadata('[F-v3-resource-reference-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-resource-reference-id-invalid]': ErrorCodeMetadata('[F-v3-resource-reference-id-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-resource-reference-path-invalid]': ErrorCodeMetadata('[F-v3-resource-reference-path-invalid]', 'FATAL', ('编译期', '运行期'), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-resource-reference-summary-missing]': ErrorCodeMetadata('[F-v3-resource-reference-summary-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-resource-reference-not-found]': ErrorCodeMetadata('[F-v3-resource-reference-not-found]', 'FATAL', ('运行期',), 'docs/engine/mvp1/02-mechanism/05-run-inner/04-tools/mvp1-alignment.md#3-接口契约'),
    '[F-v3-resource-example-invalid]': ErrorCodeMetadata('[F-v3-resource-example-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-resource-example-id-invalid]': ErrorCodeMetadata('[F-v3-resource-example-id-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-resource-example-path-missing]': ErrorCodeMetadata('[F-v3-resource-example-path-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-resource-example-path-invalid]': ErrorCodeMetadata('[F-v3-resource-example-path-invalid]', 'FATAL', ('编译期', '运行期'), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-resource-example-summary-missing]': ErrorCodeMetadata('[F-v3-resource-example-summary-missing]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
    '[F-v3-resource-example-not-found]': ErrorCodeMetadata('[F-v3-resource-example-not-found]', 'FATAL', ('运行期',), 'docs/engine/mvp1/02-mechanism/05-run-inner/04-tools/mvp1-alignment.md#3-接口契约'),
    '[F-v3-reference-reader-failed]': ErrorCodeMetadata('[F-v3-reference-reader-failed]', 'WARN', ('装配期',), 'docs/engine/mvp1/02-mechanism/03-assemble/mvp1-alignment.md#2-数据流--机制'),
    '[F-v3-resolver-skill-id-invalid]': ErrorCodeMetadata('[F-v3-resolver-skill-id-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/02-mechanism/02-resolver/mvp1-alignment.md#3-接口契约'),
    '[F-v3-skill-id-ambiguous]': ErrorCodeMetadata('[F-v3-skill-id-ambiguous]', 'FATAL', ('编译期', '装配期'), 'docs/engine/mvp1/02-mechanism/02-resolver/mvp1-alignment.md#3-接口契约'),
    '[F-v3-skill-not-registered]': ErrorCodeMetadata('[F-v3-skill-not-registered]', 'FATAL', ('编译期', '装配期'), 'docs/engine/mvp1/02-mechanism/02-resolver/mvp1-alignment.md#3-接口契约'),
    '[F-v3-resolver-path-invalid]': ErrorCodeMetadata('[F-v3-resolver-path-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/02-mechanism/02-resolver/mvp1-alignment.md#3-接口契约'),
    '[F-v3-resolver-interface-invalid]': ErrorCodeMetadata('[F-v3-resolver-interface-invalid]', 'FATAL', ('编译期',), 'docs/engine/mvp1/02-mechanism/02-resolver/mvp1-alignment.md#3-接口契约'),
    '[F-v3-resolver-missing]': ErrorCodeMetadata('[F-v3-resolver-missing]', 'FATAL', ('运行期',), 'docs/engine/mvp1/02-mechanism/02-resolver/mvp1-alignment.md#3-接口契约'),
    '[F-v3-cognitive-slot-render-failed]': ErrorCodeMetadata('[F-v3-cognitive-slot-render-failed]', 'FATAL', ('装配期',), 'docs/engine/mvp1/02-mechanism/03-assemble/mvp1-alignment.md#2-数据流--机制'),
    '[F-v3-cognitive-output-schema-render-failed]': ErrorCodeMetadata('[F-v3-cognitive-output-schema-render-failed]', 'FATAL', ('装配期',), 'docs/engine/mvp1/02-mechanism/03-assemble/mvp1-alignment.md#2-数据流--机制'),
    '[F-v3-cognitive-output-schema-invalid]': ErrorCodeMetadata('[F-v3-cognitive-output-schema-invalid]', 'FATAL', ('装配期', '装配前'), 'docs/engine/mvp1/02-mechanism/03-assemble/mvp1-alignment.md#2-数据流--机制'),
    '[F-v3-reference-reader-input-invalid]': ErrorCodeMetadata('[F-v3-reference-reader-input-invalid]', 'FATAL', ('装配期',), 'docs/engine/mvp1/02-mechanism/03-assemble/mvp1-alignment.md#2-数据流--机制'),
    '[F-v3-reference-reader-output-invalid]': ErrorCodeMetadata('[F-v3-reference-reader-output-invalid]', 'FATAL', ('装配期',), 'docs/engine/mvp1/02-mechanism/03-assemble/mvp1-alignment.md#2-数据流--机制'),
    '[F-v3-tool-argument-invalid]': ErrorCodeMetadata('[F-v3-tool-argument-invalid]', 'FATAL', ('运行期',), 'docs/engine/mvp1/02-mechanism/05-run-inner/04-tools/mvp1-alignment.md#3-接口契约'),
    '[F-v3-runtime-state-mapping-failed]': ErrorCodeMetadata('[F-v3-runtime-state-mapping-failed]', 'FATAL', ('运行期',), 'docs/engine/mvp1/02-mechanism/04-run-outer/01-graph-exec/mvp1-alignment.md#3-接口契约'),
    '[F-v3-runtime-phase-failed]': ErrorCodeMetadata('[F-v3-runtime-phase-failed]', 'FATAL', ('运行期',), 'docs/engine/mvp1/02-mechanism/04-run-outer/01-graph-exec/mvp1-alignment.md#3-接口契约'),
    '[F-v3-sequential-overwrite-unauthorized]': ErrorCodeMetadata('[F-v3-sequential-overwrite-unauthorized]', 'FATAL', ('编译期',), 'docs/engine/mvp1/01-contract/02-skill-syntax/mvp1-alignment.md#2-语法部件清单--mvp1-写入状态'),
}


__all__ = ["ERROR_REGISTRY", "ErrorCodeMetadata"]
